// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honnix.crm.domain;

import com.honnix.crm.domain.CartOrderDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CartOrderDataOnDemand_Roo_Configurable {
    
    declare @type: CartOrderDataOnDemand: @Configurable;
    
}
