// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honnix.crm.domain;

import com.honnix.crm.domain.CartOrder;
import com.honnix.crm.domain.CartOrderDataOnDemand;
import com.honnix.crm.domain.CartOrderIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CartOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CartOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CartOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CartOrderIntegrationTest: @Transactional;
    
    @Autowired
    private CartOrderDataOnDemand CartOrderIntegrationTest.dod;
    
    @Test
    public void CartOrderIntegrationTest.testCountCartOrders() {
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", dod.getRandomCartOrder());
        long count = CartOrder.countCartOrders();
        Assert.assertTrue("Counter for 'CartOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CartOrderIntegrationTest.testFindCartOrder() {
        CartOrder obj = dod.getRandomCartOrder();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to provide an identifier", id);
        obj = CartOrder.findCartOrder(id);
        Assert.assertNotNull("Find method for 'CartOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CartOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CartOrderIntegrationTest.testFindAllCartOrders() {
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", dod.getRandomCartOrder());
        long count = CartOrder.countCartOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'CartOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CartOrder> result = CartOrder.findAllCartOrders();
        Assert.assertNotNull("Find all method for 'CartOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CartOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CartOrderIntegrationTest.testFindCartOrderEntries() {
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", dod.getRandomCartOrder());
        long count = CartOrder.countCartOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CartOrder> result = CartOrder.findCartOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CartOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CartOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CartOrderIntegrationTest.testFlush() {
        CartOrder obj = dod.getRandomCartOrder();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to provide an identifier", id);
        obj = CartOrder.findCartOrder(id);
        Assert.assertNotNull("Find method for 'CartOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCartOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CartOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartOrderIntegrationTest.testMergeUpdate() {
        CartOrder obj = dod.getRandomCartOrder();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to provide an identifier", id);
        obj = CartOrder.findCartOrder(id);
        boolean modified =  dod.modifyCartOrder(obj);
        Integer currentVersion = obj.getVersion();
        CartOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CartOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CartOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", dod.getRandomCartOrder());
        CartOrder obj = dod.getNewTransientCartOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CartOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CartOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CartOrderIntegrationTest.testRemove() {
        CartOrder obj = dod.getRandomCartOrder();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CartOrder' failed to provide an identifier", id);
        obj = CartOrder.findCartOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CartOrder' with identifier '" + id + "'", CartOrder.findCartOrder(id));
    }
    
}
